"""Update booking model with array of room ids

Revision ID: 0904fd461e53
Revises: f40c781575d6
Create Date: 2025-05-20 10:47:04.875209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0904fd461e53'
down_revision: Union[str, None] = 'f40c781575d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_rooms', schema='hotelassistant')
    op.add_column('bookings', sa.Column('rooms', postgresql.ARRAY(sa.UUID()), nullable=False), schema='hotelassistant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'rooms', schema='hotelassistant')
    op.create_table('booking_rooms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['hotelassistant.bookings.id'], name='booking_rooms_booking_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['hotelassistant.rooms.id'], name='booking_rooms_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='booking_rooms_pkey'),
    schema='hotelassistant'
    )
    # ### end Alembic commands ###
