"""Add created_at to Message model

Revision ID: 4891e701c341
Revises: 0904fd461e53
Create Date: 2025-05-20 19:43:45.256447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4891e701c341'
down_revision: Union[str, None] = '0904fd461e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.Date(), nullable=False), schema='hotelassistant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at', schema='hotelassistant')
    # ### end Alembic commands ###
